// React/src/protect-routes/Auth_Guard.js
import React from 'react';
import { Navigate, Outlet } from 'react-router-dom';

export default function Auth_Guard(){
    const isToken = localStorage.getItem('token') != null?true:false

    if(isToken){
        return <Navigate to="/dashboard" />
        
    }else{    
        return <Outlet />
    }
}

// Angular/src/app/services/auth-guard/auth.guard.ts
import { Injectable } from '@angular/core';
import {
  ActivatedRouteSnapshot,
  CanActivate,
  RouterStateSnapshot,
  UrlTree,
} from '@angular/router';
import { Observable } from 'rxjs';
import { Router } from '@angular/router';

@Injectable({
  providedIn: 'root',
})
export class AuthGuard implements CanActivate {
  constructor(private router: Router) {}
  canActivate(
    route: ActivatedRouteSnapshot,
    state: RouterStateSnapshot
  ):
    | Observable<boolean | UrlTree>
    | Promise<boolean | UrlTree>
    | boolean
    | UrlTree {
    var isToken = localStorage.getItem('token') !== null ? true : false;
    if (isToken) {
      this.router.navigate(['/dashboard']);
    }

    return !isToken;
  }
}
