// React/src/components/Register.jsx
import React from "react";
import { useFormik } from "formik";
import { SignupValidations } from "../form-validations/FormValidations";
import "./Register.css";
import { userSignup } from "../services/auth.service";
import { useNavigate } from "react-router-dom";
import { toast } from "react-toastify";

const initialValues = {
  first_name: "",
  last_name: "",
  add_line1: "",
  add_line2: "",
  state: "",
  city: "",
  mobile: "",
  email: "",
  password: "",
  confirmPassword: "",
};

const state = [
  "Maharashtra",
  "Gujrat",
  "Uttar Pradesh",
  "Bihar",
  "Maddhya Pradesh",
];

const city = [
  "Mumbai",
  "Pune",
  "Nagpur",
  " Wardha",
  "Mandgaon",
  "Ramtek",
  " Amravati",
];

const Register = () => {
  const navigate = useNavigate();
  const { values, errors, touched, handleChange, handleSubmit, handleReset } =
    useFormik({
      initialValues: initialValues,
      validationSchema: SignupValidations,
      onSubmit: async (values) => {
        const res = await userSignup(values);
        if (res.data.status) {
          toast.success(res.data.message);
          navigate("/dashboard");
        } else {
          toast.error(res.data.message);
        }
      },
    });

  return (
    <>
      <div className="container register">
        <div className="row">
          <div className="col-md-3 register-left">
            <h3>Welcome</h3>
            <br />
            <input
              type="submit"
              name=""
              value="Login"
              onClick={() => navigate("/login")}
            />
            <br />
          </div>
          <div className="col-md-9 register-right">
            <div className="tab-content" id="myTabContent">
              <div
                className="tab-pane fade show active"
                id="home"
                role="tabpanel"
                aria-labelledby="home-tab"
              >
                <form className="row register-form" onSubmit={handleSubmit}>
                  <div className="col-md-6">
                    <div className="form-group">
                      <input
                        type="text"
                        className="form-control"
                        placeholder="first Name"
                        value={values?.first_name}
                        name="first_name"
                        onChange={handleChange}
                      />
                      {errors.first_name && touched.first_name ? (
                        <p className="text-danger">{errors.first_name}</p>
                      ) : null}
                    </div>

                    <div className="form-group">
                      <input
                        type="text"
                        className="form-control"
                        placeholder="Address Line1"
                        value={values?.add_line1}
                        name="add_line1"
                        onChange={handleChange}
                      />
                      {errors.add_line1 && touched.add_line1 ? (
                        <p className="text-danger">{errors.add_line1}</p>
                      ) : null}
                    </div>
                    <div className="form-group">
                      <select
                        name="state"
                        className="form-control"
                        onChange={handleChange}
                        style={{ display: "block" }}
                      >
                        <option>Select State</option>
                        {state.map((data, i) => (
                          <option key={i}>{data}</option>
                        ))}
                      </select>
                      {errors.state && touched.state ? (
                        <p className="text-danger">{errors.state}</p>
                      ) : null}
                    </div>
                    <div className="form-group">
                      <input
                        type="number"
                        className="form-control"
                        placeholder="Mobile"
                        value={values?.mobile}
                        name="mobile"
                        onChange={handleChange}
                      />
                      {errors.mobile && touched.mobile ? (
                        <p className="text-danger">{errors.mobile}</p>
                      ) : null}
                    </div>
                    <div className="form-group">
                      <input
                        type="password"
                        className="form-control"
                        placeholder="Password"
                        value={values?.password}
                        name="password"
                        onChange={handleChange}
                      />
                      {errors.password && touched.password ? (
                        <p className="text-danger">{errors.password}</p>
                      ) : null}
                    </div>
                  </div>
                  <div className="col-md-6">
                    <div className="form-group">
                      <input
                        type="text"
                        className="form-control"
                        placeholder="Last Name"
                        value={values?.last_name}
                        name="last_name"
                        onChange={handleChange}
                      />
                      {errors.last_name && touched.last_name ? (
                        <p className="text-danger">{errors.last_name}</p>
                      ) : null}
                    </div>
                    <div className="form-group">
                      <input
                        type="text"
                        className="form-control"
                        placeholder="Address Line2"
                        value={values?.add_line2}
                        name="add_line2"
                        onChange={handleChange}
                      />
                    </div>
                    <div className="form-group">
                      <select
                        name="city"
                        className="form-control"
                        onChange={handleChange}
                      >
                        <option>Select City</option>
                        {city.map((data, i) => (
                          <option key={i}>{data}</option>
                        ))}
                      </select>
                      {errors.city && touched.city ? (
                        <p className="text-danger">{errors.city}</p>
                      ) : null}
                    </div>
                    <div className="form-group">
                      <input
                        type="email"
                        className="form-control"
                        placeholder="Email"
                        value={values?.email}
                        name="email"
                        onChange={handleChange}
                      />
                      {errors.email && touched.email ? (
                        <p className="text-danger">{errors.email}</p>
                      ) : null}
                    </div>

                    <div className="form-group">
                      <input
                        type="password"
                        className="form-control"
                        placeholder="Confirm Password"
                        value={values?.confirmPassword}
                        name="confirmPassword"
                        onChange={handleChange}
                      />
                      {errors.confirmPassword && touched.confirmPassword ? (
                        <p className="text-danger">{errors.confirmPassword}</p>
                      ) : null}
                      {!errors.confirmPassword && touched.confirmPassword? (
                        <p className="text-success">Password Matched</p>
                      ) : null}
                    </div>
                  </div>
                  <button className="btn btn-info" type="submit">
                    Submit
                  </button>
                  <button className="btn btn-danger" onClick={handleReset}>
                    Reset
                  </button>
                </form>
              </div>
              <div
                className="tab-pane fade show"
                id="profile"
                role="tabpanel"
                aria-labelledby="profile-tab"
              >
                <h3 className="register-heading">Apply as a Hirer</h3>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Register;

// Angular/src/app/register/register.component.ts
import { Component, OnInit } from '@angular/core';
import { ApiService } from '../services/api-service/api.service';
import { Router } from '@angular/router';
import { FormGroup, FormBuilder, Validators } from '@angular/forms';
import { ToastrService } from 'ngx-toastr';
import { MustMatch } from '../services/form-validations/mustmatch';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css'],
})
export class RegisterComponent implements OnInit {
  states:any=['Maharashtra',"bihar","Uttar Pradesh","Lucknow"]
  cities:any = [
    "Mumbai",
    "Pune",
    "Nagpur",
    " Wardha",
    "Mandgaon",
    "Ramtek",
    " Amravati",
  ];
  registerForm: any = FormGroup;
  submitted = false;
  confirmedPassword: any;

  constructor(
    private formBuilder: FormBuilder,
    private service: ApiService,
    private router: Router,
    private toastr: ToastrService,
  ) {}

  ngOnInit(): void {
    this.registerForm = this.formBuilder.group(
      {
        first_name: [
          '',
          [Validators.required, Validators.pattern('^[a-zA-Z]*$')],
        ],
        last_name: [
          '',
          [Validators.required, Validators.pattern('^[a-zA-Z ]*$')],
        ],
        add_line1: ['', [Validators.required]],
        add_line2: [''],
        state: ['', [Validators.required]],
        city: ['', [Validators.required]],
        mobile: [
          '',
          [
            Validators.required,
            Validators.pattern('^((\\+91-?)|0)?[0-9]{10}$'),
          ],
        ],
        email: [
          '',
          [
            Validators.required,
            Validators.pattern('[a-z0-9._%+-]+@[a-z0-9.-]+.[a-z]{2,4}$'),
          ],
        ],
        password: ['', [Validators.required, Validators.minLength(8)]],
        confirmPassword: ['', [Validators.required]],
      },
      {
        validator: MustMatch('password', 'confirmPassword')
    }
    );
  }

  get form() {
    return this.registerForm.controls;
  }

  changeState(e: any) {
    console.log("Stae",e.target.value)
    this.registerForm.state = e.target.value
  }

  changeCity(e: any) {
    console.log("City",e.target.value)
    this.registerForm.city = e.target.value
  }

  handleSubmit() {
    console.log("SubmitData",this.registerForm.value)
    this.service.userSignup(this.registerForm.value).then((res: any) => {
      if (res.status === true) {
        this.toastr.success(res.message, 'Success');
        this.router.navigate(['/dashboard']);
      } else {
        this.toastr.error(res.message, 'Error');
      }
    });
  }

  handleReset() {
    this.registerForm.reset();
    this.submitted = false;
  }
}

<div class="container register">
  <div class="row">
    <div class="col-md-3 register-left">
      <h3>Welcome</h3>
      <br /><br /><br />
    </div>
    <div class="col-md-9 register-right">
      <ul class="nav nav-tabs nav-justified" id="myTab" role="tablist">
        <li class="nav-item">
          <a
            class="nav-link active"
            id="home-tab"
            data-toggle="tab"
            href="#home"
            role="tab"
            aria-controls="home"
            aria-selected="true"
            >Registration</a
          >
        </li>
        <li class="nav-item">
          <a
            class="nav-link"
            id="profile-tab"
            data-toggle="tab"
            href="#profile"
            first
            role="tab"
            aria-controls="profile"
            aria-selected="false"
            >Login</a
          >
        </li>
      </ul>

      <div class="tab-content" id="myTabContent">
        <div
          class="tab-pane fade show active"
          id="home"
          role="tabpanel"
          aria-labelledby="home-tab"
        >
          <form [formGroup]="registerForm">
            <div class="row register-form">
              <div class="col-md-6">
                <div class="form-group">
                  <input
                    type="text"
                    name="first_name"
                    placeholder="First Name"
                    formControlName="first_name"
                    class="form-control"
                  />
                  <div
                    class="error"
                    *ngIf="form.first_name.errors && form.first_name.touched"
                  >
                    <div *ngIf="form.first_name.errors.required">
                      First name is required *
                    </div>
                    <div *ngIf="form.first_name.errors.pattern">
                      Only alphabets allowed!!!
                    </div>
                  </div>
                </div>
                <div class="form-group">
                  <input
                    type="text"
                    name="add_line1"
                    placeholder="Address Line 1"
                    formControlName="add_line1"
                    class="form-control"
                  />
                  <span
                    class="error"
                    *ngIf="form.add_line1.invalid && form.add_line1.touched"
                    >Address Line1 is required *</span
                  >
                </div>
                <div class="form-group">
                  <!-- <input
                    type="text"
                    name="state"
                    placeholder="State"
                    formControlName="state"
                    class="form-control"
                  />
                  <span
                    class="error"
                    *ngIf="form.state.invalid && form.state.touched"
                    >State is required *</span
                  > -->
                  <select
                    class="custom-select mb-3"
                    (change)="changeState($event)"
                    formControlName="state"
                    class="form-control"
                  >
                    <option value="">Select state</option>
                    <option *ngFor="let state of states" [ngValue]="state">
                      {{ state }}
                    </option>
                  </select>
                  <span
                    class="error"
                    *ngIf="form.state.invalid && form.state.touched"
                    >State is required *</span
                  >
                </div>
                <div class="form-group">
                  <input
                    type="number"
                    name="mobile"
                    placeholder="Mobile No."
                    formControlName="mobile"
                    class="form-control"
                  />
                  <div
                    *ngIf="form.mobile.touched && form.mobile.errors"
                    class="error"
                  >
                    <div *ngIf="form.mobile.errors.required">
                      Mobile Number is required *
                    </div>
                    <div *ngIf="form.mobile.errors.pattern">
                      Please, Enter 10 digit Mobile Number.
                    </div>
                  </div>
                </div>
                <div class="form-group">
                  <input
                    type="password"
                    name="password"
                    placeholder="Password *"
                    formControlName="password"
                    class="form-control"
                  />
                  <div
                    class="error"
                    *ngIf="form.password.errors && form.password.touched"
                  >
                    <div *ngIf="form.password.errors.required">
                      Password is required *
                    </div>
                    <div *ngIf="form.password.errors.minlength">
                      Password should be of minimum 8 character!!
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <input
                    type="text"
                    name="last_name"
                    placeholder="Last Name"
                    formControlName="last_name"
                    class="form-control"
                  />
                  <div
                    class="error"
                    *ngIf="form.last_name.errors && form.last_name.touched"
                  >
                    <div *ngIf="form.last_name.errors.required">
                      Last name is required *
                    </div>
                    <div *ngIf="form.last_name.errors.pattern">
                      Only alphabets allowed!!!
                    </div>
                  </div>
                </div>
                <div class="form-group">
                  <input
                    type="text"
                    name="add_line2"
                    class="form-control"
                    placeholder="Address Line 2 (optional)"
                    formControlName="add_line2"
                  />
                </div>
                <div class="form-group">
                  <select
                  class="custom-select mb-3"
                  (change)="changeCity($event)"
                  formControlName="city"
                  class="form-control"
                >
                  <option value="">Select City</option>
                  <option *ngFor="let city of cities" [ngValue]="city">
                    {{ city }}
                  </option>
                </select>
                  <span
                    class="error"
                    *ngIf="form.city.invalid && form.city.touched"
                    >City is required *</span
                  >
                </div>
                <div class="form-group">
                  <input
                    type="email"
                    name="email"
                    placeholder="Email"
                    formControlName="email"
                    class="form-control"
                    [ngClass]="{
                      'is-invalid': form.email.touched && form.email.errors
                    }"
                  />

                  <div
                    class="error"
                    *ngIf="form.email.errors && form.email.touched"
                  >
                    <div *ngIf="form.email.errors.required">
                      Email is required *
                    </div>
                    <div *ngIf="form.email.errors.pattern">
                      Enter a valid email!!!
                    </div>
                  </div>
                </div>

                <div class="form-group">
                  <input
                    type="password"
                    name="confirmPassword"
                    placeholder="Confirm Password *"
                    formControlName="confirmPassword"
                    class="form-control"
                  />
                  <div
                    class="error"
                    *ngIf="
                      form.confirmPassword.errors &&
                      form.confirmPassword.touched
                    "
                  >
                    <div *ngIf="form.confirmPassword.errors.required">
                      Please confirm password
                    </div>
                    <div *ngIf="form.confirmPassword.errors?.mustMatch">
                      Passwords must match
                    </div>
                  </div>
                  <div
                    class="text-success"
                    *ngIf="!form.confirmPassword.errors"
                  >
                    Password Matched
                  </div>
                </div>

                <br />
              </div>
            </div>
          </form>
          <div class="text-right">
            <button
              [disabled]="registerForm.invalid"
              class="btnRegister"
              (click)="handleSubmit()"
            >
              Submit
            </button>
            <button class="btnReset" (click)="handleReset()">Reset</button
            >&nbsp;&nbsp;
          </div>
        </div>
      </div>
    </div>
    <div class="text-right">
      <b>Already registered?<a routerLink="/login"> Login here</a></b>
    </div>
  </div>
</div>
