// Angular/src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { ApiService } from '../services/api-service/api.service';
import { ToastrService } from 'ngx-toastr';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
})
export class LoginComponent implements OnInit {
  user = { email: '', password: '' };

  constructor(
    private service: ApiService,
    private router: Router,
    private toastr: ToastrService
  ) {}

  ngOnInit(): void {}

  onSubmit(data: any) {
    this.service.userLogin(data).then((res) => {
      if (res.status) {
        this.toastr.success(res.message, 'Success');
        this.router.navigate(['/dashboard']);
      } else {
        this.toastr.error(res.message, 'Error!');
      }
    });
  }
}

<section class="vh-100">
  <div class="container py-5 h-100">
    <div class="row d-flex align-items-center justify-content-center h-100">
      <div class="col-md-8 col-lg-7 col-xl-6">
        <img
          src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.svg"
          class="img-fluid"
          alt="Phone image"
        />
      </div>
      <div class="col-md-7 col-lg-5 col-xl-5 offset-xl-1">
        <form #loginForm="ngForm" (ngSubmit)="onSubmit(loginForm.value)">
          <!-- Email input -->
          <div class="form-outline mb-4">
            <label class="form-label" for="form1Example13">Email address</label>
            <input
              type="email"
              name="email"
              ngModel
              #email="ngModel"
              pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$"
              class="form-control form-control-lg"
              required
            />
            <div *ngIf="email.touched">
              <p class="error" *ngIf="email.errors?.['required']">
                Email is required *
              </p>
              <p class="error" *ngIf="email.errors?.['pattern']">
                Enter a valid email!!!
              </p>
            </div>
          </div>

          <!-- Password input -->
          <div class="form-outline mb-4">
            <label class="form-label" for="form1Example23">Password</label>

            <input
              required
              #password="ngModel"
              [(ngModel)]="user.password"
              type="password"
              name="password"
              class="form-control form-control-lg"
              minlength="3"
              maxlength="8"
            />
            <span class="error" *ngIf="password.invalid && password.touched"
              >Password is required *</span
            >
          </div>

          <div class="d-flex justify-content-around align-items-center mb-4">
            <!-- Checkbox -->
            <div class="form-check"></div>
            Do not have account?
            <a routerLink="/register">Signup Here</a>
          </div>

          <!-- Submit button -->
          <button
            type="submit"
            class="btn btn-primary btn-lg btn-block"
            [disabled]="loginForm.invalid"
          >
            Sign in
          </button>

          <div class="divider d-flex align-items-center my-4">
            <p class="text-center fw-bold mx-3 mb-0 text-muted">OR</p>
          </div>

          <a
            class="btn btn-primary btn-lg btn-block"
            style="background-color: #3b5998"
            href="#!"
            role="button"
          >
            <i class="fab fa-facebook-f me-2"></i>Continue with Facebook
          </a>
          <a
            class="btn btn-primary btn-lg btn-block"
            style="background-color: #55acee"
            href="#!"
            role="button"
          >
            <i class="fab fa-twitter me-2"></i>Continue with Twitter</a
          >
        </form>
      </div>
    </div>
  </div>
</section>

// React/src/components/Login.jsx
import React from "react";
import "./Login.css";
import {
  MDBContainer,
  MDBCol,
  MDBRow,
  MDBBtn,
  MDBIcon,
  MDBInput,
} from "mdb-react-ui-kit";
import { userLogin } from "../services/auth.service";
import { toast } from "react-toastify";
import { useNavigate } from "react-router-dom";
import { useFormik } from "formik";
import { LoginValidations } from "../form-validations/FormValidations";

const initialValues = {
  email: "",
  password: "",
};

const Login = () => {
  const navigate = useNavigate();
  const { values, errors, touched, handleChange, handleSubmit } = useFormik({
    initialValues: initialValues,
    validationSchema: LoginValidations,
    onSubmit: async (values) => {
      const res = await userLogin(values);
      if (res.data.status) {
        toast.success(res.data.message);
        navigate("/dashboard");
      } else {
        toast.error(res.data.message);
      }
    },
  });

  return (
    <>
      <MDBContainer fluid className="p-3 my-5 h-custom">
        <MDBRow>
          <MDBCol col="10" md="6">
            <img
              src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
              className="img-fluid"
              alt="Sample image"
            />
          </MDBCol>

          <MDBCol col="4" md="6">
            <div className="d-flex flex-row align-items-center justify-content-center">
              <p className="lead fw-normal mb-0 me-3">Sign in with</p>

              <MDBBtn floating size="md" tag="a" className="me-2">
                <MDBIcon fab icon="facebook-f" />
              </MDBBtn>

              <MDBBtn floating size="md" tag="a" className="me-2">
                <MDBIcon fab icon="twitter" />
              </MDBBtn>

              <MDBBtn floating size="md" tag="a" className="me-2">
                <MDBIcon fab icon="linkedin-in" />
              </MDBBtn>
            </div>

            <div className="divider d-flex align-items-center my-4">
              <p className="text-center fw-bold mx-3 mb-0">Or</p>
            </div>

            <MDBInput
              wrapperclass="mb-4"
              placeholder="Email"
              type="email"
              size="lg"
              name="email"
              onChange={handleChange}
            />
            {errors.email && touched.email ? (
              <p className="text-danger">{errors.email}</p>
            ) : null}
            <br />
            <MDBInput
              wrapperclass="mb-4"
              placeholder="Password"
              type="password"
              size="lg"
              name="password"
              onChange={handleChange}
            />
            {errors.password && touched.password ? (
              <p className="text-danger">{errors.password}</p>
            ) : null}

            <div className="text-center text-md-start mt-4 pt-2">
              <MDBBtn
                type="button"
                className="mb-0 px-3"
                onClick={() => handleSubmit()}
              >
                Login
              </MDBBtn>
              <p className="small fw-bold mt-2 pt-1 mb-2">
                Don't have an account?{" "}
                <a
                  className="link-danger"
                  onClick={() => navigate("/register")}
                >
                  Register
                </a>
              </p>
            </div>
          </MDBCol>
        </MDBRow>

        <div className="d-flex flex-column flex-md-row text-center text-md-start justify-content-between py-4 px-4 px-xl-5 bg-primary">
          <div className="text-white mb-3 mb-md-0">
            Copyright © 2020. All rights reserved.
          </div>

          <div>
            <MDBBtn
              tag="a"
              color="none"
              className="mx-3"
              style={{ color: "white" }}
            >
              <MDBIcon fab icon="facebook-f" size="md" />
            </MDBBtn>

            <MDBBtn
              tag="a"
              color="none"
              className="mx-3"
              style={{ color: "white" }}
            >
              <MDBIcon fab icon="twitter" size="md" />
            </MDBBtn>

            <MDBBtn
              tag="a"
              color="none"
              className="mx-3"
              style={{ color: "white" }}
            >
              <MDBIcon fab icon="google" size="md" />
            </MDBBtn>

            <MDBBtn
              tag="a"
              color="none"
              className="mx-3"
              style={{ color: "white" }}
            >
              <MDBIcon fab icon="linkedin-in" size="md" />
            </MDBBtn>
          </div>
        </div>
      </MDBContainer>
      );
    </>
  );
};

export default Login;
